- name: Print some debug information
  hosts: localhost
  vars: 
    msg: |
        Module Variables ("vars"):
        --------------------------------
        {{ vars | to_nice_json }} 
 
        Environment Variables ("environment"):
        --------------------------------
        {{ environment | to_nice_json }} 
 
        GROUP NAMES Variables ("group_names"):
        --------------------------------
        {{ group_names | to_nice_json }}
 
        GROUPS Variables ("groups"):
        --------------------------------
        {{ groups | to_nice_json }}
 
        HOST Variables ("hostvars"):
        --------------------------------
        {{ hostvars | to_nice_json }} 

  tasks:
  - name: debug1
    debug:
        msg: "{{ msg.split('\n') }}" 
    tags: debug_info1
  - name: debug2
    debug:
        var: hostvars[inventory_hostname]
    tags: debug_info2
